"""Core data types and models for the cost agent."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union

from .constants import (
    Aggregation,
    ChartType,
    SortDirection,
    SourceType,
    TimeWindowType,
)


# -----------------------------
# Core planning / query contracts
# -----------------------------


@dataclass(frozen=True)
class TimeWindow:
    """
    Represents a time window request.
    - If type == YESTERDAY: start/end are computed later.
    - If type == LAST_N_DAYS: n_days must be provided.
    - If type == RANGE: start and end must be provided (inclusive start, inclusive end by convention).
    """

    type: TimeWindowType
    n_days: Optional[int] = None
    start: Optional[date] = None
    end: Optional[date] = None


@dataclass(frozen=True)
class QueryFilters:
    """
    Filter conditions for data retrieval.
    Keep this conservative: only include fields we explicitly support.
    """

    account_id: Optional[List[int]] = None
    chat_type: Optional[List[str]] = None
    chat_id: Optional[List[str]] = None

    has_tasks: Optional[bool] = None
    has_classifications: Optional[bool] = None
    has_both: Optional[bool] = None


@dataclass(frozen=True)
class SortSpec:
    by: str
    direction: SortDirection = SortDirection.DESC


@dataclass(frozen=True)
class AggregationSpec:
    """
    Example:
      - field="total_cost", agg=SUM
      - field="account_id", agg=COUNT_DISTINCT
    """

    field: str
    agg: Aggregation
    as_name: Optional[str] = None


@dataclass(frozen=True)
class QuerySpec:
    """
    A backend-agnostic query description that can be executed on CSV (now) or Postgres (later).
    """

    time_window: TimeWindow
    filters: QueryFilters = field(default_factory=QueryFilters)
    group_by: List[str] = field(default_factory=list)
    aggregations: List[AggregationSpec] = field(default_factory=list)
    sort: Optional[SortSpec] = None
    top_n: Optional[int] = None
    max_rows: Optional[int] = None


@dataclass(frozen=True)
class Lineage:
    """
    Metadata describing how a table was produced (auditability & reproducibility).
    """

    source_type: SourceType
    dataset_name: str
    dataset_version: str  # e.g., CSV file hash or DB snapshot id
    generated_at_utc: datetime
    time_window: TimeWindow
    applied_filters: Dict[str, Any]
    group_by: List[str]
    row_count: int
    notes: Optional[str] = None


# -----------------------------
# Report templates & outputs
# -----------------------------


@dataclass(frozen=True)
class ChartSpec:
    """
    Declarative chart spec. In MVP you may only use a subset.
    """

    id: str
    type: ChartType
    table: str  # evidence table name
    title: Optional[str] = None

    # generic fields to support common chart mappings
    x: Optional[str] = None
    y: Optional[Union[str, List[str]]] = None
    label: Optional[str] = None
    value: Optional[str] = None


@dataclass(frozen=True)
class ReportTemplate:
    """
    Loaded from report_templates.yaml.
    """

    template_id: str
    title: str
    description: str
    time_window: TimeWindow
    evidence_tables: List[str]
    charts: List[ChartSpec]
    constraints: Dict[str, Any] = field(default_factory=dict)
    required_filters: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class RunArtifacts:
    """
    Paths to output artifacts generated by a run.
    """

    run_id: str
    output_dir: str
    dashboard_png: Optional[str] = None
    summary_txt: Optional[str] = None
    evidence_dir: Optional[str] = None
    run_record_json: Optional[str] = None


@dataclass(frozen=True)
class RunRecord:
    """
    Saved to outputs/.../run_record.json for reproducibility and evaluation.
    """

    run_id: str
    started_at_utc: datetime
    finished_at_utc: Optional[datetime]
    mode: Literal["button", "ad_hoc"]
    template_id: Optional[str]
    user_input: Optional[str]
    query_specs: List[QuerySpec]
    lineage: List[Lineage]
    artifacts: RunArtifacts
    verifier: Dict[str, Any] = field(default_factory=dict)
    notes: Dict[str, Any] = field(default_factory=dict)
